# Generated by Django 3.0.6 on 2020-06-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeconfig_app', '0002_auto_20200603_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
